'$schema' = 'https://starship.rs/config-schema.json'
add_newline = true
continuation_prompt = '[❯❯ ](bold green)'
format = '$os$username$hostname$localip$shlvl$singularity$kubernetes$directory$vcsh$fossil_branch$fossil_metrics$git_branch$git_commit$git_state$git_metrics$git_status$hg_branch$pijul_channel$package$fill$all'
palette = 'catppuccin_latte'

[character]
  error_symbol = '[❯](bold red)'
  success_symbol = '[❯](bold green)'

[directory]
  fish_style_pwd_dir_length = 3
  style = 'bold sapphire'
  truncation_symbol = '.../'

[fill]
  symbol = '-'

[git_branch]
  style = 'bold pink'

[git_commit]
  tag_disabled = false
  tag_symbol = '  '

[os]
  disabled = false

  [os.symbols]
    Arch = '[ ](bold #1793d1)'
    Debian = '[ ](bold #a80030)'
    Macos = '[ ](bold #a2aaad)'

[package]
  disabled = true

[palettes]
  [palettes.catppuccin_latte]
    base = '#eff1f5'
    blue = '#1e66f5'
    crust = '#dce0e8'
    flamingo = '#dd7878'
    green = '#40a02b'
    lavender = '#7287fd'
    mantle = '#e6e9ef'
    maroon = '#e64553'
    mauve = '#8839ef'
    overlay0 = '#9ca0b0'
    overlay1 = '#8c8fa1'
    overlay2 = '#7c7f93'
    peach = '#fe640b'
    pink = '#ea76cb'
    red = '#d20f39'
    rosewater = '#dc8a78'
    sapphire = '#209fb5'
    sky = '#04a5e5'
    subtext0 = '#6c6f85'
    subtext1 = '#5c5f77'
    surface0 = '#ccd0da'
    surface1 = '#bcc0cc'
    surface2 = '#acb0be'
    teal = '#179299'
    text = '#4c4f69'
    yellow = '#df8e1d'

  [palettes.catppuccin_macchiato]
    base = '#24273a'
    blue = '#8aadf4'
    crust = '#181926'
    flamingo = '#f0c6c6'
    green = '#a6da95'
    lavender = '#b7bdf8'
    mantle = '#1e2030'
    maroon = '#ee99a0'
    mauve = '#c6a0f6'
    overlay0 = '#6e738d'
    overlay1 = '#8087a2'
    overlay2 = '#939ab7'
    peach = '#f5a97f'
    pink = '#f5bde6'
    red = '#ed8796'
    rosewater = '#f4dbd6'
    sapphire = '#7dc4e4'
    sky = '#91d7e3'
    subtext0 = '#a5adcb'
    subtext1 = '#b8c0e0'
    surface0 = '#363a4f'
    surface1 = '#494d64'
    surface2 = '#5b6078'
    teal = '#8bd5ca'
    text = '#cad3f5'
    yellow = '#eed49f'

[username]
  show_always = true
  style_user = 'bold sky'
