[opener]
document = [
  { run = 'zathura "$@"', block = false, orphan = true, for = 'unix' }
]
text = [
  { run = '"$EDITOR" "$@"', block = true, orphan = false, for = 'unix' }
]

[open]
rules = [
  { name = '*.pdf', use = 'document' },
  { name = '*.epub', use = 'document' },
  { name = '*.csv', use = 'text'},
  { name = '*.txt', use = 'text'}
]

[mgr]
linemode = "size"
show_symlink = true
