# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$fill\
$all\
"""

# Inserts a blank line between shell prompts
add_newline = true

continuation_prompt = '[❯❯ ](bold green)'

palette = "catppuccin_latte"

[fill]
symbol = '-'


[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

# Replace the '❯' symbol in the prompt with ' '
[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "bold sapphire"
truncation_symbol = ".../"
fish_style_pwd_dir_length = 3

[git_branch]
style = "bold pink"

[git_commit]
tag_disabled = false
tag_symbol = "  "

[username]
show_always = true
style_user = "bold sky"

[os]
disabled = false

[os.symbols]
Debian = "[ ](bold red)"
